/*
 * generated by Xtext 2.18.0
 */
package app.hypermedia.testing.dsl.tests

import app.hypermedia.testing.dsl.core.ClassBlock
import app.hypermedia.testing.dsl.core.Model
import com.google.inject.Inject
import org.eclipse.xtext.testing.InjectWith
import org.eclipse.xtext.testing.extensions.InjectionExtension
import org.eclipse.xtext.testing.util.ParseHelper
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.^extension.ExtendWith

import static org.junit.Assert.assertEquals
import app.hypermedia.testing.dsl.core.PropertyBlock
import app.hypermedia.testing.dsl.core.PropertyStatement

@ExtendWith(InjectionExtension)
@InjectWith(CoreInjectorProvider)
class PropertyParsingTest {
    @Inject
    ParseHelper<Model> parseHelper

    @Test
    def void withProperty_parsesName() {
        // when
        val result = parseHelper.parse('''
            With Class "Person" {
                With Property "name" {
                }
            }
        ''')

        // then
        TestHelpers.assertModelParsedSuccessfully(result)

        val classBlock = result.steps.get(0) as ClassBlock
        val propertyBlock = classBlock.children.get(0) as PropertyBlock
        assertEquals(propertyBlock.name, "name")
    }

    @Test
    def void expectProperty_parsesWithoutChildren() {
        // when
        val result = parseHelper.parse('''
            With Class "Person" {
                Expect Property "name"
            }
        ''')

        // then
        TestHelpers.assertModelParsedSuccessfully(result)

        val classBlock = result.steps.get(0) as ClassBlock
        val propertyStmt = classBlock.children.get(0) as PropertyStatement
        assertEquals(propertyStmt.name, "name")
    }
}
